### ISSUE TITLE
Request: Optionally show password on the device

### ISSUE THREAD

**Issue by riordant** [LedgerHQ/app-passwords#13]
Unfortunately Android often does not seen to work, despite trying different keyboard layouts. As a result, optionally show the password on the device so that it can be typed manually.

**Comment by btchip** [comment]
Can you describe what's the issue ?

**Comment by TamtamHero** [comment]
Is this still happening with latest version (>1.0.0) ?

**Comment by erjoalgo** [comment]
Someone commented on the same issue here:

https://www.reddit.com/r/ledgerwallet/comments/k154rr/using_ledger_passwords_app_on_android/

I too have not been able to get this to work on android. 

I also agree it should be possible to display the password on the Ledger. Imagine that you are having an emergency, your phone died and you need to order a Uber back home; a stranger is willing to lend you their Uber app on their own phone but you still can't log in to your account because you don't have a USB-C cable.

Or you are in a foreign country and your phone was just stolen. Your friend has a back-up phone, you try to log out of your gmail account on all devices and change your password before the thieves break into your account. But you don't have a USB cable or for whatever reason password typing isn't working on your friend's phone.

**Comment by MartCern** [comment]
Would be real nice to have a "Display password" option next to "Type password" as I primarily use iPhone and i would love to use my Ledger Nano X as passwords storage that I could use on the go. Thanks a million if this goes live :)

**Comment by riordant** [comment]
Unlikely given their history, but worth a try.

**Comment by TamtamHero** [comment]
Should be released next Monday 
https://github.com/LedgerHQ/app-passwords/pull/30
As always, be careful, don't forget to make a backup of your app with https://blog.ledger.com/passwords-backup/ before doing the update.

**Comment by MartCern** [comment]
Thank you so much! Looking forward! I'll test it immediately :)

**Comment by TamtamHero** [comment]
Released :tada: 
**Don't forget to backup first !  https://blog.ledger.com/passwords-backup/ **
